### ISSUE TITLE
Additional integration tests

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-js#55]
# Happy path

Common
--
- [x] Can create several instances on a language client #75 
- [x] Clients can send parallel requests (DDL, select, insert stream, insert array) #75  

Configuration
--
- [x] Can connect to ClickHouse with the default configuration
- [x] Can create an HTTPS connection
- [x] Can specify default database name on creation #76 
- [x] Can configure ClickHouse settings for every client request #76 
- [x] Can provide a custom logger class on creation #76 
- [x] Language client does not mutate provided configuration #76 

Insert & Select
--
- [x] Can perform several parallel requests #77
- [x] Cancellation of one of the parallel requests does not cancel the others #77
- [x] A query resulting in a single row
- [x] A query resulting in a dataset of X rows
- [x] A dataset of several rows with all the language primitives #78 
- [x] A test suit for each supported ClickHouse Data Type (Enum, Map, UInt 256, etc.) #78 
- [x] A stream of text data (TSV or ndjson)
- [x] A test suit for Insert and Select for chosen [supported format](https://clickhouse.com/docs/en/interfaces/formats/) #83 
- [x] Insert and Select a DateTime as a number, string, or Date object in a timezone different from the server's one #82 
- [x] A result dataset containing `toDateTime` conversion to a time zone different from the client's one #82 
- [x] Can send a query with parameters
- [x] Can send a query with non-ASCII symbols #80 
- [x] Can send a query with parameters containing non-ASCII symbols #80 
- [x] Can send a query with parameters containing DateTime / Date #80 
- [x] Can send a query with enums in parameters #80 
- [x] A query with a response summary
- [x] A query with query-specific settings taking precedence over instance-specific settings
- [x] Accepts a compressed response
- [x] Sends a compressed request
- [x] Can send a multiline query
- [x] Can send a query with an inline comment
- [x] Can send a query with a multiline comment
- [x] Can send a query with a comment on a trailing line
- [x] Ignores unknown properties during `insert` https://github.com/ClickHouse/clickhouse-js/pull/83

Insert
--
- [x] A stream of text data (TSV, CSV)
- [x] A stream of data objects

Select
--
- [x] A query that results in an empty response #79
- [x] Sends a stream of data (TSV or ndjson)
- [x] A query with a response in [JSON format (with JSON default settings)](https://clickhouse.com/docs/en/interfaces/formats/#json-formats-settings) 
- [x] [optional] A query with a response with totals, extremes, meta, statistics fields
- [x] A query can be canceled before it is sent
- [x] A query can be canceled after it is sent
- [x] A query can be canceled while reading the response
- [x] A query can be canceled while inserting data into ClickHouse
- [x] Make sure the ClickHouse server cancels a query on cancellation on the client level
- [x] Can consume the result of Select response only once #79

Command
--
- [x] Can send a query with parameters #80 
 
 
# Unhappy path (client reports ClickHouse errors and does not crash)

Insert & select
--
- [x] Provides configuration error details (malformed host URL)
- [x] Provides error details when sending a query with unknown setting/parameters #82 
- [x] Provides details of the authentication error
- [x] Provides details of Timeout error
- [x] Provides details of a syntax error
- [x] Provides details of network error #82 
- [x] Throws an exception when inserting data in an incorrect format https://github.com/ClickHouse/clickhouse-js/pull/83
- [x] Throws an exception when inserting data with an incorrect type  https://github.com/ClickHouse/clickhouse-js/pull/83

Insert
--
- [x] Provides error details on an exception raised during Insert (a dataset with an invalid type) #82 

Select
--
- [x] An exception during Select (Select from a non-existing database, parsing error)
